### ISSUE TITLE
AirPlay is broken in 10.7 unstable

### ISSUE THREAD

**Issue by nyanmisaka** [jellyfin/jellyfin-web#2066]
**Describe The Bug**
Nothing happends after clicking the AirPlay button.

**Steps To Reproduce**
1. Play a video in Safari.
2. Click the AirPlay button.
3. Nothing happends.

**Expected Behavior**
AirPlay works in 10.6.4 stable.

**System (please complete the following information):**
 - Platform: iOS 14.2, iPad OS 14.2
 - Browser: Safari and Jellyfin iOS App
 - Jellyfin Version: 10.7 unstable

**Comment by nyanmisaka** [comment]
@anthonylavado 
Since I'm not only using iOS, could you help me to try this on Mac OS? Thanks.

**Comment by anthonylavado** [comment]
I still haven't tested on macOS, but I suspect it will be the same issue (it's supposed to be the same code).

**Comment by anthonylavado** [comment]
I can confirm that AirPlay is broken in 10.7.0, using Safari  14.0.1 (16610.2.11.51.8) on macOS Big Sur 11.0.1 (20B29).

The error message in the Safari console is:
```
TypeError: this.isAirPlayEnabled is not a function. (In 'this.isAirPlayEnabled()', 'this.isAirPlayEnabled' is undefined)
```
It lists `toggleAirplay` in plugin.js.

**Comment by anthonylavado** [comment]
Here is the Apple Documentation, if anyone wants to look at it: https://developer.apple.com/documentation/webkitjs/adding_an_airplay_button_to_your_safari_media_controls
