### ISSUE TITLE
JASSUB doesn't work in legacy browsers

### ISSUE THREAD

**Issue by dmitrylyzo** [jellyfin/jellyfin-web#4794]
**Describe The Bug**
JASSUB doesn't work in legacy browsers: worker fails on webOS 1.2, requiring `fetch`, `Promise` (probably more).

**Steps To Reproduce**
1. Run app in webOS 1.2 emulator using `ares-inspect`.
2. Open ares-inspect address in the Chrome 79 (newer may work too).
3. Start playback of video with ASS subtitles.
4. See error in the console.

**Expected Behavior**
No error and see subtitles.

**System (please complete the following information):**
 - Platform: webOS 1.2
 - Browser: Jellyfin webOS app
 - Jellyfin Version: 10.9

**Additional Context**
Promise in webOS 2 has a weird implementation, so it also requires testing.
JASSUB 1.5.13 works fine, because it was built with compatibility flags (browser version).

**Comment by ThaUnknown** [comment]
this is.... unusual?

jassub only uses fetch for engines which support streamed WASM compilation, which REQUIRES fetch in the engine to work, as it uses fetch responses, so if fetch doesnt exist, streamed compilation will never run, and never call fetch, so it's a non-issue?

**Comment by ThaUnknown** [comment]
![image](https://github.com/jellyfin/jellyfin-web/assets/6506529/837b75f0-3d48-400a-9196-2424a33209fa)
also I can't get JF to even play any media to test this :&

**Comment by ThaUnknown** [comment]
I couldn't get JF-web to work, so I simply [copied its webpack config](https://github.com/ThaUnknown/jassub/blob/gh-pages/webpack.config.js) and hosted it on [my test page](https://thaunknown.github.io/jassub/jassub/legacy/index.html), it works on chrome 76, but I can't really test webOS:
![image](https://github.com/jellyfin/jellyfin-web/assets/6506529/f20a5886-2635-47aa-9769-07749bf00b02)

**Comment by ThaUnknown** [comment]
the worker always required transpiration, [this isn't new](https://github.com/jellyfin/jellyfin-web/pull/4357/files#diff-3e31f6f375484b2dfd4629faed9e5183ac6568ebdbc67ec752e10c41a35250c6R185-R198), I'll look into missing globals when using strict, or I could remove use strict which I think is added by vite [as always causes problems]

also I don't see why it would cry about WebAssembly missing, if it doesn't exist it should error inside the trycatch, and polyfill it, and the next time it's ran it's already defined

I see the issue with promise tho, that's annoying

**Comment by ThaUnknown** [comment]
I think promise needs to be polyfilled in worker, [I tried](https://github.com/ThaUnknown/jellyfin-web/tree/jassub-regression), but I'm faily sure I failed

**Comment by ThaUnknown** [comment]
I'm fairly sure I fixed all these issues in 1.7.7

**Comment by dmitrylyzo** [comment]
> I'm fairly sure I fixed all these issues in 1.7.7

JASSUB 1.7.7 doesn't work in Chrome 79
```
Uncaught (in promise) RangeError: WebAssembly.Table.get(): invalid index 584944 into function table
    at ae (http://.../jellyfin/web/176e75238a0c18a53cdd.js:480:74)
    at Dr (http://.../jellyfin/web/176e75238a0c18a53cdd.js:1142:16)
    at wasm-function[722]:0xa18b4
    at wasm-function[747]:0xa68eb
    at wasm-function[870]:0xea152
    at Ir (http://.../jellyfin/web/176e75238a0c18a53cdd.js:1159:9)
    at http://.../jellyfin/web/176e75238a0c18a53cdd.js:1173:197
```

It doesn't work on webOS 1.2: it loads `jassub-worker.wasm.js`, but then it also loads `data.wasmUrl`, which is `jassub-worker.wasm`.

**Comment by ThaUnknown** [comment]
*audible confusion*

**Comment by dmitrylyzo** [comment]
webOS 1.2:
```js
    function Rr(t, r, n) {
      var i = Ce();
      try {
        return ae(t)(r, n);
      } catch (o) {
        if (we(i), o !== o + 0) throw o;
        me(1, 0);
      }
    }
    function Dr(t, r, n, i, o) {
      var u = Ce();
      try {
        return ae(t)(r, n, i, o);    // TypeError: 'undefined' is not a function (evaluating 'ae(t)(r, n, i, o)') 
      } catch (p) {
        if (we(u), p !== p + 0) throw p;
        me(1, 0);
      }
    }
    function Wr(t, r, n, i) {
      var o = Ce();
      try {
        return ae(t)(r, n, i);
      } catch (u) {
        if (we(o), u !== u + 0) throw u;
        me(1, 0);
      }
    }
    f.getTempRet0 = tt, f.setTempRet0 = et;
    function Ir(t) {
      t.M();
    }
    var Ze = {
        a: Ur
      },
      We,
      J,
      Ne,
      me,
      et,
      tt,
      Ce,
      we;
    return (WebAssembly.instantiateStreaming ? WebAssembly.instantiateStreaming(fetch("jassub-worker-modern.wasm"), Ze) : WebAssembly.instantiate(f.wasm, Ze)).then(function (t) {
      C = (t.instance || t).exports, f._malloc = We = C.N, J = C.O, Ne = C.P, f.__embind_initialize_bindings = C.Q, me = C.S, et = C.T, tt = C.U, Ce = C.V, we = C.W, C.X, C.Y, C.Z, C._, ue = C.R, Ir(C), P();
    }), f.ready;
  }(f);
```

Chrome 79:
```js
    function Lt(t, r, n) {
      f.hasOwnProperty(t) || ge("Replacing nonexistant public symbol"), f[t].overloadTable !== void 0 && n !== void 0 ? f[t].overloadTable[n] = r : (f[t] = r, f[t].argCount = n);
    }
    function Ht(t, r, n) {
      var i = dynCalls[t];
      return n && n.length ? i.apply(null, [r].concat(n)) : i.call(null, r);
    }
    var be = [];
    function ae(t) {
      var r = be[t];
      return r || (t >= be.length && (be.length = t + 1), be[t] = r = ue.get(t)), r;    // RangeError: WebAssembly.Table.get(): invalid index 584944 into function table
    }
    function Bt(t, r, n) {
      if (t.includes("j")) return Ht(t, r, n);
      var i = ae(r).apply(null, n);
      return i;
    }
    function xt(t, r) {
      var n = [];
      return function () {
        return n.length = 0, Object.assign(n, arguments), Bt(t, r, n);
      };
    }
    function q(t, r) {
      t = I(t);
      function n() {
        return t.includes("j") ? xt(t, r) : ae(r);
      }
      var i = n();
      return typeof i != "function" && _("unknown function pointer with signature ".concat(t, ": ").concat(r)), i;
    }
```
Does JASSUB 1.7.7 work in Chrome 76 for you?

**Comment by ThaUnknown** [comment]
the issue is some emscripten bug, I've downgraded emscripten and I think it should fix this issue, the chrome 76 bug is worrying, as that implies the C compiled code errored, which hasnt been changed in months

**Comment by ThaUnknown** [comment]
you can try `npm install https://github.com/thaunknown/jassub` and see if it errors

**Comment by dmitrylyzo** [comment]
I tested latest `jassub/main` (https://github.com/ThaUnknown/jassub/commit/36eb3d76ffa9195aa589673deae6e21312547aa2) in Chrome 79 - works.

Regarding webOS 1.2 and transpilation, there is some [warning](https://webpack.js.org/guides/web-workers/) about using variables when constructing Worker.
> Using a variable in the Worker constructor is not supported by webpack. For example, the following code will not work: const url = new URL('./path/to/worker.ts', import.meta.url); const worker = new Worker(url);. This is because webpack cannot analyse the syntax statically. It is important to be aware of this limitation when using Worker syntax with webpack.

Could this be the reason it isn't transpiled?

**Comment by ThaUnknown** [comment]
The worker is being transpiled by webpack because of the babel loader config as you saw yourself, the function and variable names are mangled, I think it's honestly some stupid emscripten bug, and it's starting to annoy me

**Comment by ThaUnknown** [comment]
@dmitrylyzo okay, with v1.7.8 I've 100% confirmed that legacy works again, I didn't have time to check if it worked previously or not but I'm sure it works now, if it still doesn't work then it's likely because of the transpilation done by babel

**Comment by ThaUnknown** [comment]
@dmitrylyzo could you test 1.7.8? if it still errors, any you get any errors, send them, I'm fairly sure it's gonna be caused by the wasm.js worker being broken by babel so I'll simply have to exclude it

**Comment by dmitrylyzo** [comment]
Worker (1.7.8, 1.7.9) now requires a polyfill for `Array.prototype.copyWithin` (webOS 1.2).

**Comment by ThaUnknown** [comment]
wth

**Comment by ThaUnknown** [comment]
minor oversight, fixed in 1.7.10

**Comment by dmitrylyzo** [comment]
> minor oversight, fixed in 1.7.10

Now the same error as https://github.com/jellyfin/jellyfin-web/issues/4794#issuecomment-1732431567
> TypeError: 'undefined' is not a function (evaluating 'ie(t)(r, n, i, o)')

Also, I have different output files when building from source (`main` branch) - it fails ES check (arrow-functions). It seems the build infra differs.

**Comment by ThaUnknown** [comment]
okay, so babel is definetly at fault here, if you copy over the worker.wasm.js file from jassub's dist and replace it in jellyfin-web's folder, tho you'd need to rename it to some hash that webpack uses for the file, and it should work

If this still doesn't work, then this is a JS engine error, as it runs correctly on newer chrome engines, and the error you referenced is emitted in the WASM emulation, which means somehow on older engines, the JS is executed differently, because the WASM steps should be the same, giga yikes

did you use docker to compile? the output should be the same

where is the ES check failed? it should fail in worker and main, but not in .wasm.js

**Comment by ThaUnknown** [comment]
I'll have some time this weekend to look into this, but from what you described: this is bad, really bad, in summary the JS engine webOS 1.2 uses evaluates things differently?

JASSUB doesn't do any transpilation, it's on the end developer to transpile the code JASSUB provides, which jellyfin already has a config for and does

at most the JASSUB rebuild should ONLY differ from the npm store with stuff like new lines, and nothing else, I cleaned out my ubuntu install, tried running this again, and I get the same output as what the NPM store has

give me a few hours and I'll look deeper

**Comment by ThaUnknown** [comment]
either there was something critically wrong with my wsl install, or I lack some basic understanding of how it works but I had a lot of issues with files being cached and not updated, not sure what happened, it's fixed

it's as I feared, babel is transpiling the JS files, and breaking the WASM, which is the root of the issue, I'm however at my wit's end as to how to disable that, static copy doesn't seem to work as expected, and the worker keeps changing, I tried changing this behavior but I keep failing, not sure why: https://github.com/ThaUnknown/jellyfin-web/tree/static-wasm.js
left is what's outputed by webpack's static copy, right is original from node_modules
![image](https://github.com/jellyfin/jellyfin-web/assets/6506529/0308dc87-2edb-47e6-8409-8fb0eb99d652)

**Comment by ThaUnknown** [comment]
TIL, production mode makes Terser run on ALL files even statically copied ones, and since it has dead code removal..... yeah you can imagine the rest

this was up there with some of the least fun things I've had to track down in recent weeks

https://github.com/jellyfin/jellyfin-web/pull/4971

@dmitrylyzo

**Comment by ThaUnknown** [comment]
fixed in jassub 1.7.13

**Comment by ThaUnknown** [comment]
@dmitrylyzo is this now resolved on jassub's end? or is there still something I need to fix? asking cuz I want to mark this as complete on my TODO list

**Comment by dmitrylyzo** [comment]
> @dmitrylyzo is this now resolved on jassub's end? or is there still something I need to fix? asking cuz I want to mark this as complete on my TODO list

Yes, it is resolved. 🤞 At least it finally works on webOS 1.2. I am waiting for Renovate to update its PR.

**Comment by dmitrylyzo** [comment]
webOS 2 (it has a native Promise, but it is buggy - it should still be polyfilled):
`TypeError: PromiseResolver is not a function (evaluating 'h(l)')`
```
var Module = function Module() {
  var l = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : {};
  return function (l) {
    var l = l,
      h;
    l.ready = new Promise(function (t, r) {
      h = t;
    });
    var C = function C(t) {
        return console.log(t);
      },
      y = function y(t) {
        return console.error(t);
      };
    function _() {
      h(l);    // TypeError: PromiseResolver is not a function (evaluating 'h(l)')
    }
```

Tizen 5 and webOS 5:
`Uncaught (in promise) CompileError: WasmCompile: Wasm decoding failed: unexpected section: Code @+4549`
```
return (WebAssembly.instantiateStreaming ? WebAssembly.instantiateStreaming(fetch("jassub-worker-modern.wasm"), Ze) : WebAssembly.instantiate(l.wasm, Ze)).then(function (t) {
```
^ loading `jassub-worker.wasm`

**Comment by ThaUnknown** [comment]
I added a fix for engines which pretend that promise is supported [I don't understand how resolve in promise can not be a function], but I was not able to reproduce the webOS 5 error so I'm not sure whats wrong
