### ISSUE TITLE
`r.map is not a function` when accessing Dashboard

### ISSUE THREAD

**Issue by HammyHavoc** [jellyfin/jellyfin-web#8190]
### Description of the bug

Visiting https://media.splitanatom.com/web/#/dashboard produces a sequence of error messages.

### Reproduction steps

1. Visit the Dashboard.

### What is the current _bug_ behavior?

See above.

### What is the expected _correct_ behavior?

That the Dashboard functions. :- )

### Jellyfin Server version

Unstable

### Specify the build version

https://hub.docker.com/layers/jellyfin/jellyfin/unstable/images/sha256-d976dbdc198d8b33dc545f480040be32767d992295d813bf653ff71ed94283b6

### Environment

```markdown
- OS: Unraid
- Linux Kernel:
- Virtualization: Docker
- Clients:
- Browser: LibreWolf
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- CPU Model:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Jellyfin Data Storage & Filesystem:
- Media Storage & Filesystem:
- External Integrations:
```

### Jellyfin logs

```shell
Unexpected Application Error!
r.map is not a function

he@https://192.168.1.102/web/6496.43c2f6779c025656f564.chunk.js:1:8319
hu@https://192.168.1.102/web/node_modules.react-dom.bundle.js?54073350d410fb081a51:2:60311
xi@https://192.168.1.102/web/node_modules.react-dom.bundle.js?54073350d410fb081a51:2:119252
bs@https://192.168.1.102/web/node_modules.react-dom.bundle.js?54073350d410fb081a51:2:108506
vs@https://192.168.1.102/web/node_modules.react-dom.bundle.js?54073350d410fb081a51:2:108434
gs@https://192.168.1.102/web/node_modules.react-dom.bundle.js?54073350d410fb081a51:2:108295
as@https://192.168.1.102/web/node_modules.react-dom.bundle.js?54073350d410fb081a51:2:105130
ls@https://192.168.1.102/web/node_modules.react-dom.bundle.js?54073350d410fb081a51:2:103686
S@https://192.168.1.102/web/1133.bundle.js?54073350d410fb081a51:2:48298
C@https://192.168.1.102/web/1133.bundle.js?54073350d410fb081a51:2:48829
@https://192.168.1.102/web/node_modules.core-js.bundle.js?54073350d410fb081a51:1:73377
k@https://192.168.1.102/web/node_modules.core-js.bundle.js?54073350d410fb081a51:1:73145
P@https://192.168.1.102/web/node_modules.core-js.bundle.js?54073350d410fb081a51:1:73205
```

### FFmpeg logs

```shell

```

### Additional information

I'm not the only person to have this issue: https://www.reddit.com/r/jellyfin/comments/1ucjd0b/comment/otcucdo/

They started seeing it with RC1.

Can't see the Dashboard, so can't tell you the exact build number, but it's latest unstable following 12.0 RC2 via Docker, which should be https://hub.docker.com/layers/jellyfin/jellyfin/unstable/images/sha256-d976dbdc198d8b33dc545f480040be32767d992295d813bf653ff71ed94283b6

**Comment by Selari** [comment]
Also having this issue, not sure if it's related to upgrading to Debian Trixie 13.6 today.

Server is 12.0-rc2.

Worked on Debian 13.5

**Comment by azureeeeeee23** [comment]
Happening to us as well , anyone figured it out yet?

**Comment by Shadowghost** [comment]
Did you clear the browser cache after upgrading to 12.x?

**Comment by thornbill** [comment]
I haven't been able to replicate this. Please provide a list of any plugins you have installed.

**Comment by vicky5124** [comment]
I can reproduce the issue when accessing through a domain behind nginx, but I do not get this when accessing directly via the local ip and port. I can temporarily fix it by logging out and logging back in, but the issue presents itself again when restarting the server.

**Comment by Selari** [comment]
I haven't been able to re-replicate this bug. I cleared my browser-cache on the local domain for my jellyfin and that seemed to fix the issue, been on -rc3 since release and not been seen.

**Comment by BookOfGreg** [comment]
This happens to my jellyfin also, 12.0.0, no plugins installed.

**Comment by fmarcac** [comment]
I reproduced this in nginx and caddy by serving static web files without bypassing it for `/web/ConfigurationPages` and `/web/ConfigurationPage`. Both examples can be fixed by not serving static files at all since jellyfin already does it or adding special routes for those two paths.
  Nginx:
```nginx
location /web/ {
    # /web/ConfigurationPages mapped to /usr/share/jellyfin-web/ConfigurationPages, doesn't exist
    alias /usr/share/jellyfin-web/;
    try_files $uri $uri/ /web/index.html;
}
location / {
    proxy_pass http://jellyfin:8096;
}
```
Fix by bypassing serving of static files on these routes:
```nginx
location = /web/ConfigurationPages {
    proxy_pass http://jellyfin:8096;
    proxy_set_header Host $host;
}
location = /web/ConfigurationPage  {
    proxy_pass http://jellyfin:8096;
    proxy_set_header Host $host;
}
# ... rest of config
```
Caddy:
```caddyfile
# same as above, /web/ConfigurationPages mapped to /usr/share/jellyfin-web/ConfigurationPages
handle_path /web/* {
    root * /usr/share/jellyfin-web
    try_files {path} /index.html
    file_server
}
handle {
    reverse_proxy jellyfin:8096
}
```
Again, fix is to add two handles for those routes:
```caddyfile
handle /web/ConfigurationPages {
    reverse_proxy jellyfin:8096
}
handle /web/ConfigurationPage {
    reverse_proxy jellyfin:8096
}
# ... rest of config
```

Can't confirm this is exactly what is causing the reporters' issues, so anyone affected should confirm or deny they are serving static files.
Dashboard error itself is caused by the request being answered with HTML by the proxy instead of reaching the endpoint and a missing guard in `fetchConfigurationPages` in `src/apps/dashboard/features/plugins/api/useConfigurationPages.ts` then causes a crash, which when added would instead return an empty array so items just don't display.  A more permanent fix is to add new routes to backend that aren't served from /web/ (while keeping the old ones to not break plugins and clients) since only those two are there, then change the routes used by the client to harden against misconfigurations, but that's a bigger change.

This issue should be reopened imo, if only for the missing guard fix if that's acceptable

**Comment by jessielw** [comment]
I was having the same issue. I've not done anything different with my setup and it was working fine until today randomly since updating to v12 on release date. I couldn't access the dashboard at all - clearing cache and cookies however did resolve it for now.

**Comment by VirtualDisk** [comment]
I had the same issue, only I am running Jellyfin on Kubernetes behind Istio. I needed to use an envoyFilter to fix. Once I fixed it on the proxy layer I needed to clear browser cache. Hoping the fix sticks this time, it seems to be intermittent. 

```
-- The match has to be made on the request,
-- where `:authority` still exists, and read
-- back on the response.
-- Only a top-level navigation may be turned
-- into the page. An XHR that gets an HTML
-- body instead of its JSON crashes the
-- caller: jellyfin-web's dashboard drawer
-- maps over the body of
-- /web/ConfigurationPages with no guard and
-- dies with `r.map is not a function`
-- (jellyfin/jellyfin-web#8190), leaving the
-- whole dashboard on an error boundary until
-- a reload after warm-up. Browsers send
-- `sec-fetch-dest: document` for a real
-- navigation; anything else keeps the
-- upstream 5xx, which is what an API caller
-- can handle. Old clients that send no
-- Sec-Fetch-* fall back to the Accept
-- header.
local function is_navigation(handle)
  local dest = handle:headers():get("sec-fetch-dest")
  if dest ~= nil then
    return dest == "document"
  end
  local accept = handle:headers():get("accept") or ""
  return string.find(accept, "text/html", 1, true) ~= nil
end
```

**Comment by Kitof** [comment]
Adding some data here, because I think there's a second cause in this thread that has nothing to do with the reverse proxy misconfig described above.

I'm on 12.1.0 in Docker behind Traefik, but Traefik is doing plain reverse proxying: no static file serving, no path-based routing, nothing that could shadow `/web/ConfigurationPages`. Checked that the request actually lands on the server:

```
$ curl -si 'https://myserver/web/ConfigurationPages?enableInMainMenu=true'
HTTP/2 401
server: Kestrel
```

and while logged in, from the browser console:

```js
const r = await fetch(ApiClient.getUrl('web/ConfigurationPages', { enableInMainMenu: true }), {
  headers: { Authorization: `MediaBrowser Token="${ApiClient.accessToken()}"` }
});
console.log(r.status, r.headers.get('content-type'));
console.log((await r.text()).slice(0, 300));
// 200 application/json; charset=utf-8
// []
```

Endpoint is perfectly fine, and the dashboard still blew up.

To find where exactly, I pulled the chunk from the stack trace off my own server and looked at the offset it points to (`6496.<hash>.chunk.js:1:8319`):

```js
he=function(){var e=(0,fe.q)({enableInMainMenu:!0}),r=e.data,n=e.error
...
excludePaths:null==r?void 0:r.map((function(e){return"/".concat(de.Ay.getPluginUrl(e.Name))}))
```

That's `PluginDrawerSection`, so same spot @fmarcac pointed at. The `r` in the error message is literally that minified `r`.

The interesting bit is what's in the cache. jellyfin-web persists the entire react-query cache into IndexedDB (`PersistQueryClientProvider` in `src/RootApp.tsx`, idb-keyval persister in `src/utils/query/queryClient.ts`, gcTime 24h). Dumped it:

```js
const req = indexedDB.open('keyval-store');
req.onsuccess = e => {
  const g = e.target.result.transaction('keyval').objectStore('keyval').get('jellyfin-query-cache');
  g.onsuccess = () => console.log(
    g.result?.clientState?.queries
      ?.filter(q => q.queryKey?.[0] === 'ConfigurationPages')
      .map(q => ({ key: q.queryKey, isArray: Array.isArray(q.state.data), preview: String(q.state.data).slice(0, 150) }))
  );
};
// [{ key: ["ConfigurationPages", true], isArray: false, preview: "" }]
```

The cached data is the empty string. Not null, not undefined, so `pagesInfo?.map` doesn't short-circuit and you get `r.map is not a function`.

An empty string ends up there when the endpoint answers 2xx with an empty body: axios can't `JSON.parse("")`, `silentJSONParsing` swallows the error and hands back the raw string, the promise resolves happily and the value gets cached. That's a lot easier to hit behind a proxy than on a direct connection, because the proxy has already committed the `200` before it starts relaying the body. If upstream dies mid-response you get a clean, complete, empty `200` instead of the network error you'd have gotten talking to Kestrel directly.

Then persistence turns that one-off blip into something permanent. It's restored from IndexedDB on every load, and restored data never goes through the query function, so it goes straight to render and crashes. For 24h, with the timer resetting on every reload. That's why clearing browser data fixes it, why it comes back for some people, and why it's basically impossible to reproduce on demand.

Anyone stuck right now, in the console:

```js
indexedDB.open('keyval-store').onsuccess = e =>
  e.target.result.transaction('keyval', 'readwrite').objectStore('keyval').delete('jellyfin-query-cache');
```

then hard refresh. Fixed it for me instantly, no server side change.

For an actual fix I think `useConfigurationPages.ts` needs two things and not one:

- an `Array.isArray` check in `fetchConfigurationPages`, so junk never makes it into the cache in the first place
- `select: data => Array.isArray(data) ? data : []` on the query, because the first one does nothing for people whose cache is already poisoned, that data bypasses the query function entirely

The `select` also covers `usePluginDetails` and `plugin.tsx`, which call `.filter` on the same data through `findBestConfigurationPage` and would die the same way.

Happy to open a PR if that sounds reasonable, and that this also resolves the issue for other users.

(Note : Claude Code helped me with the diagnosis and the English translation)

**Comment by angus-mackenzie** [comment]
This fixed it for me too on 12.1. I was getting `u.forEeach is not a function` on the Plugins page after adding a plugin repository. I reproduced it in both Zen and Firefox, clearing `jellyfin-query-cache` and hard-refreshing fixed it immediately. 

I was accessing Jellyfin over its tailscale hostname (<host>.ts.net:8096) just in case the connection method turns out to be relevant. Thanks!
